apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runtime.agentic-layer.ai_agentgateways.yaml
  - runtime.agentic-layer.ai_agentgatewayclasses.yaml
  - runtime.agentic-layer.ai_agents.yaml
