---
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: Agent
metadata:
  name: mocked-agent-exposed-1
spec:
  image: ghcr.io/agentic-layer/mock-agent:0.6
  exposed: true
---
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: AgentGateway
metadata:
  labels:
    app.kubernetes.io/name: agent-gateway-krakend-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-gateway
spec:
  agentGatewayClassName: krakend
  envFrom:
    - configMapRef:
        name: otel-tempo-config
---
