apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: AgentGateway
metadata:
  labels:
    app.kubernetes.io/name: agent-gateway-krakend-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-gateway
spec:
  agentGatewayClassName: krakend
  replicas: 1
  timeout: 30s
